import { StyleSheet } from 'react-native';

// ============ BẢNG MÀU CHUNG (Export đầy đủ để chống lỗi undefined) ============
export const COLORS = {
  primary: '#2563EB',
  primaryDark: '#1D4ED8',
  primarySoft: '#EFF6FF',
  primaryLight: '#DBEAFE',
  background: '#F4F7FB',
  screenBg: '#F8FAFC',
  surface: '#FFFFFF',
  white: '#FFFFFF',
  black: '#000000',
  textPrimary: '#0B1220',
  textSecondary: '#64748B',
  border: '#E5EAF2',
  inputBg: '#F7F9FC',
  link: '#1769E8',
  danger: '#DC2626',
  dangerSoft: '#FEF2F2',
  success: '#16A34A',
  successSoft: '#F0FDF4',
  warning: '#D97706',
  warningSoft: '#FFFBEB',
  shadow: '#0F172A',
} as const;

// ============ TOÀN BỘ STYLE CHO PROFILE SCREEN ============
export const ProfileStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  header: {
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.textPrimary,
  },
  userCard: {
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
  },
  avatarWrapper: {
    position: 'relative',
    marginBottom: 10,
  },
  avatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
  },
  cameraBadge: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    backgroundColor: COLORS.primary,
    width: 28,
    height: 28,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: COLORS.surface,
  },
  cameraIcon: {
    fontSize: 12,
    color: COLORS.white,
  },
  userName: {
    fontSize: 20,
    fontWeight: '800',
    color: COLORS.textPrimary,
    marginBottom: 2,
  },
  userSubText: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginBottom: 8,
  },
  tierBadge: {
    backgroundColor: COLORS.warningSoft,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  tierText: {
    fontSize: 12,
    fontWeight: '700',
    color: COLORS.warning,
  },
  walletCard: {
    margin: 16,
    padding: 20,
    borderRadius: 20,
    backgroundColor: COLORS.primary,
  },
  walletTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  walletLabel: {
    color: COLORS.primaryLight,
    fontSize: 12,
    fontWeight: '600',
  },
  walletAmount: {
    color: COLORS.white,
    fontSize: 28,
    fontWeight: '900',
    marginTop: 4,
  },
  walletActions: {
    flexDirection: 'row',
    marginTop: 16,
    gap: 10,
  },
  walletBtn: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingVertical: 8,
    borderRadius: 10,
    alignItems: 'center',
  },
  walletBtnText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: '700',
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: COLORS.surface,
    marginHorizontal: 16,
    borderRadius: 14,
    padding: 4,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  tabButtonActive: {
    backgroundColor: COLORS.primary,
  },
  tabButtonText: {
    fontSize: 13,
    fontWeight: '700',
    color: COLORS.textSecondary,
  },
  tabButtonTextActive: {
    color: COLORS.white,
  },
  formContainer: {
    padding: 16,
  },
  boxContainer: {
    backgroundColor: COLORS.surface,
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: COLORS.border,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.textPrimary,
    marginBottom: 12,
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    color: COLORS.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 6,
  },
  input: {
    height: 48,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 12,
    paddingHorizontal: 14,
    fontSize: 14,
    color: COLORS.textPrimary,
    backgroundColor: COLORS.inputBg,
  },
  inputMultiline: {
    height: 80,
    textAlignVertical: 'top',
    paddingTop: 12,
  },
  orderItem: {
    marginHorizontal: 16,
    marginBottom: 12,
    padding: 16,
    borderRadius: 16,
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  orderTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  orderId: {
    fontSize: 13,
    color: COLORS.textPrimary,
    fontWeight: '700',
  },
  orderDate: {
    fontSize: 11,
    color: COLORS.textSecondary,
  },
  orderStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
  },
  orderStatusText: {
    fontSize: 11,
    fontWeight: '800',
  },
  orderDivider: {
    height: 1,
    backgroundColor: COLORS.border,
    marginVertical: 10,
  },
  productRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  productName: {
    fontSize: 13,
    color: COLORS.textPrimary,
    flex: 1,
  },
  productQty: {
    fontSize: 13,
    color: COLORS.textSecondary,
    marginLeft: 8,
  },
  orderFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: COLORS.border,
  },
  orderTotalLabel: {
    fontSize: 12,
    color: COLORS.textSecondary,
  },
  orderTotal: {
    fontSize: 15,
    fontWeight: '900',
    color: COLORS.primaryDark,
  },
  submitButton: {
    height: 50,
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  submitButtonText: {
    color: COLORS.white,
    fontSize: 14,
    fontWeight: '800',
  },
  logoutButton: {
    marginHorizontal: 16,
    marginTop: 10,
    marginBottom: 30,
    height: 50,
    backgroundColor: COLORS.dangerSoft,
    borderRadius: 14,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FECACA',
  },
  logoutButtonText: {
    color: COLORS.danger,
    fontSize: 14,
    fontWeight: '800',
  },
});